export const perlaData = [
  {
    node: {
      title: "Bakalar Lofoten namočen očišćen Perla",
      slug: "bakalar-lofoten-namocen-ociscen-perla",
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "40",
        certifikatMsc: null,
        certifikatZivjetiZdravo: true,
        featuredPerlaProduct: true,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Bakalar Lofoten namočen očišćen Perla",
        imeProizvodaDo60ZnakovaEng: "Stockfish fillets - soaked",
        jedinicaMjere: "kg",
        kataloskiBroj: "20861",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Gadus morhua",
        marketinskoImePerlaProizvodaEng: "Cod Lofoten soaked & cleaned Perla",
        marketinskoImePerlaProizvodaHr: "Bakalar Lofoten namočen očišćen Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "a",
        opisHrDo300Znakova: "a",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "8 kg",
        tezinaPoJediniciMjere: "8 kg",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20861.webp",
        },
      },
      proizvodId: 1437,
    },
  },
  {
    node: {
      title: "Temeljac riblji 450 g Perla",
      slug: "temeljac-riblji-450-g-perla",
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "20",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: true,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Temeljac riblji 450 g Perla",
        imeProizvodaDo60ZnakovaEng: "Fish stock 450 g Perla",
        jedinicaMjere: "kom",
        kataloskiBroj: "20986",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "-",
        marketinskoImePerlaProizvodaEng: "Fish stock Perla",
        marketinskoImePerlaProizvodaHr: "Temeljac riblji Perla",
        nacinSmrzavanja: "-",
        opisEngDo300Znakova: "x",
        opisHrDo300Znakova: "x",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "16 x 450g",
        tezinaPoJediniciMjere: "450 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20986.webp",
        },
      },
      proizvodId: 1434,
    },
  },
  {
    node: {
      title: "Vongole 750 g Perla",
      slug: "vongole-750-g-perla",
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "108",
        certifikatMsc: null,
        certifikatZivjetiZdravo: true,
        featuredPerlaProduct: true,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Vongole 750 g Perla",
        imeProizvodaDo60ZnakovaEng: "White whole clams 750 g Perla",
        jedinicaMjere: "kom",
        kataloskiBroj: "20841",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Meretrix lyrata",
        marketinskoImePerlaProizvodaEng: "White whole clams",
        marketinskoImePerlaProizvodaHr: "Vongole Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "s",
        opisHrDo300Znakova: "s",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "9 x 750 g",
        tezinaPoJediniciMjere: "750 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20841.webp",
        },
      },
      proizvodId: 1432,
    },
  },
  {
    node: {
      title: "Škampi za buzaru 375 g Perla",
      slug: "oslic-fileti-500-g-perla-2",
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "110",
        certifikatMsc: null,
        certifikatZivjetiZdravo: null,
        featuredPerlaProduct: true,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Škampi za buzaru 375 g Perla",
        imeProizvodaDo60ZnakovaEng: "Scampi WR 375 g. ",
        jedinicaMjere: "kom",
        kataloskiBroj: "20856",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Nephrops Norvegicus",
        marketinskoImePerlaProizvodaEng: "Scampi alla buzara",
        marketinskoImePerlaProizvodaHr: "Škampi za buzaru Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "x",
        opisHrDo300Znakova: "x",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "Pakiranje",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "6 x 375 g",
        tezinaPoJediniciMjere: "375 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20856.webp",
        },
      },
      proizvodId: 1429,
    },
  },
  {
    node: {
      title: "Sipa kockice 235 g Perla",
      slug: "sipa-kockice-235-g-perla-2",
      proizvodiInformacije: {
        aktivatorProizvoda: true,
        brojKutijaNaPaleti: "36",
        certifikatMsc: null,
        certifikatZivjetiZdravo: true,
        featuredPerlaProduct: true,
        fieldGroupName: "proizvodiInformacije",
        ifsFood: true,
        imeProizvodaDo60Znakova: "Sipa kockice 235 g Perla",
        imeProizvodaDo60ZnakovaEng: "Cuttlefish cubes 235 g Perla",
        jedinicaMjere: "kom",
        kataloskiBroj: "20835",
        kategorijaKojojProizvodPripada: "PERLA",
        latinskiNazivDo60Znakova: "Sepia officinalis",
        marketinskoImePerlaProizvodaEng: "Cuttlefish cubes Perla",
        marketinskoImePerlaProizvodaHr: "Sipa kockice Perla",
        nacinSmrzavanja: "IQF",
        opisEngDo300Znakova: "x",
        opisHrDo300Znakova: "x",
        ostaleJediniceVelicinaPecaturaBrojKomUKg: "-",
        oznakaNovo: null,
        oznakaNovoPakiranje: null,
        vrijednostOstaleVelicine: "-",
        tezinaPoJediniciMjere: "235 g",
        perlaHoreca: null,
        slikaProizvoda: {
          sourceUrl:
            "https://marikomerc.sutra.hr/wp-content/uploads/2024/10/20835.webp",
        },
      },
      proizvodId: 1428,
    },
  },
];
