import styled from "styled-components";
import { keyframes } from "styled-components";
const blink2 = keyframes`
/* ----------------------------------------------
 * Generated by Animista on 2023-12-10 20:59:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */

  from {
    opacity: 0.9;
  }
  50% {
    opacity: 0.01;
  }
  100% {
    opacity: 0.9;
  }

`;

export const WrapAll = styled.div`
  position: relative;
  z-index: 10;
  width: 100%;

  height: auto;
  display: flex;
  flex-direction: column;

  justify-content: flex-start;
  align-items: center;
  background: #1c2640;

  padding: 51px 0 69px 20px;
  @media only screen and (max-width: 550px) {
  }
`;

export const Container = styled.div`
  position: relative;
  z-index: 10;
  width: 100%;
  max-width: 1440px;
  height: 450px;
  display: flex;
  margin: 0 auto;
  border-radius: 3px;
  flex-direction: column;
  overflow: scroll;
  justify-content: flex-start;
  align-items: flex-start;
  background: radial-gradient(
    107.92% 107.92% at 1.33% 0%,
    #2b3a63 0%,
    #101628 100%
  );
  padding: 80px 0 0 80px;
  ::-webkit-scrollbar {
    display: none;
    -ms-overflow-style: none; /* IE and Edge */
    scrollbar-width: none;
  }
  @media only screen and (max-width: 550px) {
    /* padding-top: 40px;
    height: auto; */
    padding: 50px 0 0 50px;
    height: 400px;
    width: 100vw;
  }
`;
export const DashedLine = styled.div`
  position: absolute;
  z-index: 10;
  width: 100%;
  height: 3px;
  top: 59px;
  :after {
    content: "-----------------------";
    color: rgba(255, 255, 255, 0.15);
    letter-spacing: 4px; /* Use letter-spacing to increase space between dots*/
  }

  @media only screen and (max-width: 850px) {
    /* padding-top: 40px;
    height: auto; */
  }
`;
export const WrapEvents = styled.div`
  position: relative;
  z-index: 10;

  display: flex;
  margin-right: 50px;
  transition: all 1.5s cubic-bezier(0.12, 0.52, 0.2, 0.99);
  &.inViewHistory {
    left: 0px;
  }
  &.outViewHistory {
    left: -600px;
  }
  @media only screen and (max-width: 850px) {
    padding-top: 0px;
    height: auto;
    margin-right: 95px;
  }
`;
export const Icon = styled.div`
  position: absolute;
  z-index: 10;
  right: 150px;
  top: 0;
  opacity: 0.9;
  &.outViewArrow {
    opacity: 0;
  }
  &.inViewArrow {
    opacity: 1;
    animation-name: ${blink2};
    animation-duration: 2s;
    animation-iteration-count: 5;
    animation-delay: 0.2s;
  }
  @media only screen and (max-width: 850px) {
    padding-top: 40px;
    height: auto;
    top: -37px;
    /* bottom: 200px; */
  }
`;
export const Title = styled.h1`
  position: sticky;
  width: 384px;
  left: 0px;
  font-family: "Roboto Condensed", sans-serif;
  font-style: normal;
  font-weight: 700;

  font-size: 36px;

  line-height: 120%;
  /* identical to box height, or 48px */

  color: #ffffff;
  margin-bottom: 0;

  @media only screen and (max-width: 1200px) {
  }
  @media only screen and (max-width: 420px) {
  }
`;
export const WrapDogadjaj = styled.div`
  position: relative;
  z-index: 10;
  width: 263px;
  height: auto;
  display: flex;
  flex-direction: column;

  justify-content: flex-start;
  align-items: flex-start;
  @media only screen and (max-width: 850px) {
    /* padding-top: 40px;
    height: auto; */
  }
`;
export const Line = styled.div`
  position: relative;
  z-index: 10;
  background: #4299c8;
  width: 46px;
  height: 4px;
  margin-bottom: 35px;
  margin-top: 70px;
  border-radius: 2px;
  top: -2px;
  @media only screen and (max-width: 850px) {
  }
`;

export const Year = styled.h2`
  position: relative;
  z-index: 10;
  font-family: "Gilroy";
  font-style: normal;
  font-weight: 600;
  font-size: 32px;
  line-height: 44px;
  /* identical to box height, or 138% */

  color: #ffffff;
  margin: 0;
  @media only screen and (max-width: 850px) {
  }
`;

export const Text = styled.p`
  position: relative;
  z-index: 10;
  font-family: "Gilroy";
  font-style: normal;
  font-weight: 400;
  font-size: 16px;
  line-height: 140%;
  /* or 22px */

  /* Colour 100 */

  color: #b8b8b8;
  margin-top: 23px;
  width: 80%;
  @media only screen and (max-width: 850px) {
  }
`;

/* ----------------------------------------------
 * Generated by Animista on 2023-12-20 16:47:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation blink-2
 * ----------------------------------------
 */
